[package]
name = "conway-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.10.0", features = ["debug", "canvas", "tokio"] }
itertools = "0.11"
rayon = "1.8.0"
rustc-hash = "1.1.0"
tokio = { version = "1.32.0", features = ["sync"] }
tracing-subscriber = "0.3"
